/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package iug;
import Persistencia.Conexion2;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Usuario
 */
public class Ingresar extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Ingresar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        footer = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        lblTitu = new javax.swing.JLabel();
        lblCC = new javax.swing.JLabel();
        txtCC = new javax.swing.JTextField();
        lblContra = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        pss = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        body.setBackground(new java.awt.Color(29, 34, 42));

        footer.setBackground(new java.awt.Color(34, 40, 49));

        btnExit.setBackground(new java.awt.Color(34, 40, 49));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icoSalir.png"))); // NOI18N
        btnExit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addGap(24, 24, 24))
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        header.setBackground(new java.awt.Color(34, 40, 49));
        header.setForeground(new java.awt.Color(34, 40, 49));

        lblTitu.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        lblTitu.setForeground(new java.awt.Color(255, 255, 255));
        lblTitu.setText("INGRESAR");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(lblTitu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(243, 243, 243))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        lblCC.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblCC.setForeground(new java.awt.Color(255, 255, 255));
        lblCC.setText("Cedula");

        txtCC.setBackground(new java.awt.Color(151, 230, 255));

        lblContra.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblContra.setForeground(new java.awt.Color(255, 255, 255));
        lblContra.setText("Contraseña");

        btnLogin.setBackground(new java.awt.Color(151, 230, 255));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(29, 34, 42));
        btnLogin.setText("INGRESAR");
        btnLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        pss.setBackground(new java.awt.Color(151, 230, 255));

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bodyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCC, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addComponent(lblContra)
                        .addGap(346, 346, 346))
                    .addComponent(pss, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCC)
                .addGap(536, 536, 536))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCC, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCC, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblContra, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pss, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
         /**  Trae lo que puso el usuario a una variable q podamos usar    */
            String CC = txtCC.getText();
            String account_password = new String(pss.getPassword());
        /**    Conecta base de datos  */
            Conexion2 conect = new Conexion2();
            Connection conexion = conect.getConexion();

        /**  Parte verdadera valida q debe haber informacion en ambos campos ///Partte negativa hace validacion de los datos*/
            if (CC.isEmpty() || account_password.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Algun campo está vacío");
            } else {
        try {
            /**    hace consulta solo para saber si si existe tal registro lo q significaria q se le puede dar acceso  */
            String query = "SELECT * FROM clientes WHERE CC = ? AND account_password = ?";
            PreparedStatement statement = conexion.prepareStatement(query);
            statement.setString(1, CC);
            statement.setString(2, account_password);
            ResultSet resultado = statement.executeQuery();

/**    resultado es el objeto q se crea de la conculta sql y el numero (2) es la posicion de ese objeto */
            if (resultado.next()) {// Si hay un resultado
                String cedula=resultado.getString(1);
                String nombre=resultado.getString(2);
                String apellido=resultado.getString(3);
                String cumple=resultado.getString(4);
                String genero=resultado.getString(5);
                String direccion=resultado.getString(6);
                String telefono=resultado.getString(7);
                String correo=resultado.getString(8);
                String civil=resultado.getString(9);
                String tipoCuenta=resultado.getString(10);
                String numCuenta=resultado.getString(11);
                String contraseña=resultado.getString(12);
                int balance=resultado.getInt(13);
                String apertura=resultado.getString(14);
                JOptionPane.showMessageDialog(null, "Bienvenido Usuario " +nombre+ " " +apellido+ ". A continuación, tu cuenta.");
                String nuevo=nombre+" "+apellido;
                String cuenta=tipoCuenta+": "+numCuenta;
              

                this.dispose();
/**   crea y envia a una nueva vista   y envia  a "nuevo" que es el nombre del usuarioa la siguiuente vista  */
                Bienvenida vi = new Bienvenida();
                // se usan para la vista "Bienvenida"
                vi.setUser(nuevo);
                vi.setBalance(balance);
                vi.setAccount(cuenta);
                vi.setTipoCuenta(tipoCuenta);
                vi.setNumCuenta(numCuenta);
                vi.setVisible(true);
                // enviar demas datos de la consulta
                vi.setCedula(cedula);
                vi.setCumple(cumple);
                vi.setGenero(genero);
                vi.setDireccion(direccion);
                vi.setTelefono(telefono);
                vi.setCorreo(correo);
                vi.setCivil(civil);
                vi.setContra(contraseña);
                vi.setApertura(apertura);
            } else {
                //  si la cedula o la contraseña son incorrectas, manda un mensaje y no deja ingresar
                JOptionPane.showMessageDialog(null, "Cédula o contraseña incorrecta");
                txtCC.setText("");
                pss.setText("");
                conect.CerrarConexion();
            }
        } catch (SQLException e) {
            //  si hay algun error con la consulta, se muestrar en el Output o consola
            JOptionPane.showMessageDialog(null, "Error al ejecutar la consulta: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JLabel lblCC;
    private javax.swing.JLabel lblContra;
    private javax.swing.JLabel lblTitu;
    private javax.swing.JPasswordField pss;
    private javax.swing.JTextField txtCC;
    // End of variables declaration//GEN-END:variables
}
